version: '3.6'
services:
  mongo:
    container_name: ates-mongo
    image: mongo:6.0
    entrypoint:
      - bash
      - -c
      - |
        cp /config/mongo-keyfile /config/keyfile
        chmod 400 /config/keyfile
        chown mongodb -R /config/keyfile
        exec docker-entrypoint.sh $$@
    command: mongod --replSet rs --bind_ip_all --keyFile config/keyfile --quiet --logpath /dev/null
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    networks:
      - ates
    ports:
      - 27017:27017
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./apps/api/src/config/mongo-keyfile:/config/mongo-keyfile
      - type: volume
        source: mongodb
        target: /data/db
      - type: volume
        source: mongodb-cfg
        target: /data/configdb
  # mongo-replicator creates a replica set for transaction support
  mongo-replicator:
    container_name: ates-mongo-replicator
    image: mongo:6.0
    entrypoint:
      - bash
      - -c
      - |
        cd /scripts
        chmod +x /setup.sh
        bash /setup.sh
    volumes:
      - ./bin/setup.sh:/setup.sh
      - ./bin:/scripts
    environment:
      - HOST=mongo
      - PORT=27017
      - USERNAME=root
      - PASSWORD=root
      - REPLICA_SET_NAME=rs
    networks:
      - ates
    depends_on:
      - mongo
networks:
  ates:
    name: ates-network

volumes:
  mongodb:
  mongodb-cfg:
  mailer-volume:
